apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
      - name: jellyfin
        image: jellyfin/jellyfin:latest
        ports:
        - containerPort: 8096
        volumeMounts:
        - name: config
          mountPath: /config
        - name: local-media
          mountPath: /media  # This is what Jellyfin will look inside
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: jellyfin-config-pvc
      - name: local-media
        hostPath:
          path: /media/movies  # <-- CHANGE THIS TO YOUR LAPTOP FOLDER PATH
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-svc
spec:
  selector:
    app: jellyfin
  ports:
    - protocol: TCP
      port: 8096
      targetPort: 8096